---
name: POE-Component-IRC-Plugin-WWW-DoctypeGrabber
version: 0.0101
author:
  - "Zoffix <'zoffix@cpan.org'>"
abstract: plugin to display DOCTYPEs and relevant information from given pages
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  POE::Component::IRC::Plugin::BasePoCoWrap: 0.005
  POE::Component::WWW::DoctypeGrabber: 0.0101
build_requires:
  Test::More: 0
provides:
  POE::Component::IRC::Plugin::WWW::DoctypeGrabber:
    file: lib/POE/Component/IRC/Plugin/WWW/DoctypeGrabber.pm
    version: 0.0101
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
